version: "3.9"

services:
    backend:
        image: bitnami/laravel:11
        container_name: backend
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        command:
            [
                "sh",
                "-c",
                "[ -d vendor ] || composer install && php artisan serve --host=0.0.0.0 --port=8000",
            ]

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: react-frontend
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "5173:5173"
        command: ["sh", "-c", "npm install && npm run dev -- --host"]

    mysql:
        image: mysql:8.4
        container_name: folio-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: folio-redis
        ports:
            - "6379:6379"

volumes:
    mysql_data:
